CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 role VARCHAR(20) NOT NULL CHECK (role IN ('BUYER','SELLER','ADMIN')),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 seller_id BIGINT NOT NULL,
 name VARCHAR(150) NOT NULL,
 description VARCHAR(1000),
 price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
 stock_qty INT NOT NULL CHECK (stock_qty >= 0),
 category VARCHAR(80) NOT NULL,
 image_url VARCHAR(500),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_products_seller ON products(seller_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 buyer_id BIGINT NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
 total_amount DECIMAL(10,2) NOT NULL,
 payment_method VARCHAR(10) NOT NULL DEFAULT 'CASH' CHECK (payment_method IN ('UPI','CASH')),
 upi_id VARCHAR(100),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_orders_buyer ON orders(buyer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL,
 product_id BIGINT NOT NULL,
 quantity INT NOT NULL CHECK (quantity > 0),
 unit_price DECIMAL(10,2) NOT NULL,
 CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
 CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);
CREATE TABLE IF NOT EXISTS cart_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL,
 product_id BIGINT NOT NULL,
 quantity INT NOT NULL CHECK (quantity > 0),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id),
 CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(id),
 CONSTRAINT uq_cart UNIQUE(user_id, product_id)
);
CREATE INDEX IF NOT EXISTS idx_cart_user ON cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_product ON cart_items(product_id);
CREATE TABLE IF NOT EXISTS reviews (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
 comment VARCHAR(1000),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id),
 CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id),
 CONSTRAINT uq_review UNIQUE(product_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON reviews(user_id);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(10) DEFAULT 'CASH';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS upi_id VARCHAR(100);
